stages:
  - build
  - test
  - deploy

# Переменные для Docker Compose
variables:
  DB_URL: "postgresql://user:password@db:5432/traffic_db"
  COMPOSE_PROJECT_NAME: "traffic_project"
  DOCKER_DRIVER: overlay2

# Шаг 1: Сборка проекта
build:
  stage: build
  services:
    - docker:19.03.12
  script:
    # Подключаем Docker Compose и строим контейнеры
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - main  # Шаг будет выполняться только для ветки main

# Шаг 2: Тестирование
test:
  stage: test
  services:
    - docker:19.03.12
  script:
    # Запускаем тесты внутри контейнера backend
    - docker-compose exec backend pytest  # Или используйте ваш тестовый фреймворк
  only:
    - main

# Шаг 3: Деплой на сервер
deploy:
  stage: deploy
  script:
    # Деплой на сервер через Docker Compose
    - docker-compose down  # Останавливаем текущие контейнеры
    - docker-compose up -d  # Запускаем контейнеры с новой версией
  only:
    - main
  environment:
    name: production
    url: https://your-app-url.com
