name: Build, Test, and Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Этап сборки
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose  # Добавляем ссылку в /usr/bin

      - name: Build Docker images
        run: |
          docker-compose -f ./docker-compose.yml build

  # Этап тестирования
  test-job:
    runs-on: ubuntu-latest
    needs: build-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

     

      - name: Wait for services to start
        run: |
          sleep 10

      - name: Verify Prometheus is running
        run: |
          curl -s http://localhost:9090/metrics | head

  # Этап деплоя
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker-compose push
