name: Local CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Этап сборки и тестирования
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: |
          docker-compose -f ./docker-compose.yml up --build -d

      - name: Check containers status
        run: |
          docker-compose ps

      - name: Verify Redis is running
        run: |
          docker-compose exec redis redis-cli ping

      - name: Verify Prometheus is running
        run: |
          curl -s http://localhost:9090/metrics | head

      - name: Run backend tests
        run: |
          docker-compose exec backend pytest

      - name: Run frontend tests
        run: |
          docker-compose exec frontend npm test

      - name: Stop containers after tests
        if: always()
        run: |
          docker-compose down
